### ISSUE TITLE
Build a Setup Page for Creating Initial Page Settings

### ISSUE THREAD

**Issue by mainawycliffe** [looped-dev/cms#18]
When a user downloads our system, they need to be able to configure some settings for their CMS

## Goals

- Register a Site Owner (The Staff Who will be the owner of the website)

## Tasks
- [x] Expose An GrapgQL Mutation to Register Owner
- [x] Should only happens once
- [x] Expose Query to check if the setup has been completed
- [x] Check when loading the page and redirect user to dashboard
